name: Update GitLab Stats in README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Fetch GitLab Contribution Stats
        run: |
          GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
          GITLAB_HOST="gitlab.probasegroup.com"
          GITLAB_USER_ID="james"

          CURRENT_YEAR=$(date +%Y)
          LAST_YEAR=$((CURRENT_YEAR - 1))

          # Get total commits in 2025
          TOTAL_COMMITS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=pushed&after=${CURRENT_YEAR}-01-01" | jq length)

          # Get total Merge Requests (PRs)
          TOTAL_PRS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=merged&after=${CURRENT_YEAR}-01-01" | jq length)

          # Get total issues opened
          TOTAL_ISSUES=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=opened&after=${CURRENT_YEAR}-01-01" | jq length)

          # Get total contributions from last year
          TOTAL_CONTRIBUTIONS_LAST_YEAR=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?after=${LAST_YEAR}-01-01&before=${CURRENT_YEAR}-01-01" | jq length)

          # Preserve original README and update only GitLab stats section
          START_MARKER="<!-- START GITLAB STATS -->"
          END_MARKER="<!-- END GITLAB STATS -->"

          NEW_STATS=$(cat <<EOF
          $START_MARKER
          ### 🚀 My GitLab Contributions (Updated: $(date))
          - **Total Commits (2025):** $TOTAL_COMMITS  
          - **Total PRs (Merge Requests):** $TOTAL_PRS  
          - **Total Issues Opened:** $TOTAL_ISSUES  
          - **Total Contributions (Last Year - $LAST_YEAR):** $TOTAL_CONTRIBUTIONS_LAST_YEAR  
          $END_MARKER
          EOF
          )

          # Insert stats in README while keeping other content intact
          awk -v new_stats="$NEW_STATS" '
          BEGIN {found=0}
          {if ($0 == "<!-- START GITLAB STATS -->") {found=1; print new_stats; next} }
          !found {print}
          {if ($0 == "<!-- END GITLAB STATS -->") {found=0} }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit & Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

          git pull --rebase origin main  # Pull the latest changes before committing

          git add README.md
          git commit -m "Updated GitLab stats" || echo "No changes to commit"

          git push main

