name: Update GitLab Stats in README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Fetch GitLab Contribution Stats
        run: |
          GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
          GITLAB_HOST="https://git.probasegroup.com"
          GITLAB_USER_ID="james"

          # Get total commits across all projects
          TOTAL_COMMITS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=pushed" | jq '[.[] | select(.action_name=="pushed")] | length')

          # Get total merge requests created
          TOTAL_MRS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=merged" | jq length)

          # Get total issues created
          TOTAL_ISSUES=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=opened" | jq length)

          # Get personal contribution stats
          CONTRIBUTIONS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events" | jq length)

          # Update README
          echo "### 🚀 My GitLab Contributions (Updated: $(date))" > stats.md
          echo "- **Total Commits:** $TOTAL_COMMITS" >> stats.md
          echo "- **Total Merge Requests:** $TOTAL_MRS" >> stats.md
          echo "- **Total Issues Opened:** $TOTAL_ISSUES" >> stats.md
          echo "- **Total Contributions:** $CONTRIBUTIONS" >> stats.md

          mv stats.md README.md

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated GitLab stats" || echo "No changes to commit"
          git push origin main
