name: Update GitLab Stats in README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Fetch GitLab Contribution Stats
        run: |
          GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
          GITLAB_HOST="gitlab.probasegroup.com"
          GITLAB_USER_ID="james"

          # Get total commits across all projects
          TOTAL_COMMITS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=pushed" | jq '[.[] | select(.action_name=="pushed")] | length')

          # Get total merge requests created
          TOTAL_MRS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=merged" | jq length)

          # Get total issues created
          TOTAL_ISSUES=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events?action=opened" | jq length)

          # Get personal contribution stats
          CONTRIBUTIONS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://$GITLAB_HOST/api/v4/users/$GITLAB_USER_ID/events" | jq length)

          # Preserve original README and update only GitLab stats section
          START_MARKER="<!-- START GITLAB STATS -->"
          END_MARKER="<!-- END GITLAB STATS -->"

          NEW_STATS=$(cat <<EOF
          $START_MARKER
          ### 🚀 My GitLab Contributions (Updated: $(date))
          - **Total Commits:** $TOTAL_COMMITS  
          - **Total Merge Requests:** $TOTAL_MRS  
          - **Total Issues Opened:** $TOTAL_ISSUES  
          - **Total Contributions:** $CONTRIBUTIONS  
          $END_MARKER
          EOF
          )

          # Insert stats in README while keeping other content intact
          awk -v new_stats="$NEW_STATS" '
          BEGIN {found=0}
          {if ($0 == "<!-- START GITLAB STATS -->") {found=1; print new_stats; next} }
          !found {print}
          {if ($0 == "<!-- END GITLAB STATS -->") {found=0} }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated GitLab stats" || echo "No changes to commit"
          git push origin main
